// Comprehensive list of cities, states, and countries for location autocomplete
export const LOCATIONS: string[] = [
  // Major US Cities (City, ST format)
  'Atlanta, GA',
  'Austin, TX',
  'Baltimore, MD',
  'Birmingham, AL',
  'Boston, MA',
  'Buffalo, NY',
  'Charlotte, NC',
  'Chicago, IL',
  'Cincinnati, OH',
  'Cleveland, OH',
  'Columbus, OH',
  'Dallas, TX',
  'Denver, CO',
  'Detroit, MI',
  'El Paso, TX',
  'Fort Worth, TX',
  'Fresno, CA',
  'Houston, TX',
  'Indianapolis, IN',
  'Jacksonville, FL',
  'Kansas City, MO',
  'Las Vegas, NV',
  'Long Beach, CA',
  'Los Angeles, CA',
  'Louisville, KY',
  'Memphis, TN',
  'Mesa, AZ',
  'Miami, FL',
  'Milwaukee, WI',
  'Minneapolis, MN',
  'Nashville, TN',
  'New Orleans, LA',
  'New York, NY',
  'Newark, NJ',
  'Oakland, CA',
  'Oklahoma City, OK',
  'Omaha, NE',
  'Orlando, FL',
  'Philadelphia, PA',
  'Phoenix, AZ',
  'Pittsburgh, PA',
  'Portland, OR',
  'Raleigh, NC',
  'Richmond, VA',
  'Sacramento, CA',
  'Salt Lake City, UT',
  'San Antonio, TX',
  'San Diego, CA',
  'San Francisco, CA',
  'San Jose, CA',
  'Seattle, WA',
  'St. Louis, MO',
  'Tampa, FL',
  'Tucson, AZ',
  'Tulsa, OK',
  'Virginia Beach, VA',
  'Washington, DC',
  'Albuquerque, NM',
  'Anchorage, AK',
  'Arlington, TX',
  'Aurora, CO',
  'Bakersfield, CA',
  'Chandler, AZ',
  'Chesapeake, VA',
  'Colorado Springs, CO',
  'Corpus Christi, TX',
  'Durham, NC',
  'Garland, TX',
  'Gilbert, AZ',
  'Glendale, AZ',
  'Greensboro, NC',
  'Henderson, NV',
  'Hialeah, FL',
  'Honolulu, HI',
  'Irving, TX',
  'Jersey City, NJ',
  'Laredo, TX',
  'Lexington, KY',
  'Lincoln, NE',
  'Lubbock, TX',
  'Madison, WI',
  'North Las Vegas, NV',
  'Norfolk, VA',
  'Plano, TX',
  'Rochester, NY',
  'Scottsdale, AZ',
  'Spokane, WA',
  'St. Paul, MN',
  'Stockton, CA',
  'Winston-Salem, NC',
  'Boise, ID',
  'Cambridge, MA',
  'Irvine, CA',
  'New Haven, CT',
  'Hartford, CT',
  'Providence, RI',
  'Rochester, MN',
  'Ann Arbor, MI',

  // US States (for remote workers / state-level)
  'Alabama, USA',
  'Alaska, USA',
  'Arizona, USA',
  'Arkansas, USA',
  'California, USA',
  'Colorado, USA',
  'Connecticut, USA',
  'Delaware, USA',
  'Florida, USA',
  'Georgia, USA',
  'Hawaii, USA',
  'Idaho, USA',
  'Illinois, USA',
  'Indiana, USA',
  'Iowa, USA',
  'Kansas, USA',
  'Kentucky, USA',
  'Louisiana, USA',
  'Maine, USA',
  'Maryland, USA',
  'Massachusetts, USA',
  'Michigan, USA',
  'Minnesota, USA',
  'Mississippi, USA',
  'Missouri, USA',
  'Montana, USA',
  'Nebraska, USA',
  'Nevada, USA',
  'New Hampshire, USA',
  'New Jersey, USA',
  'New Mexico, USA',
  'New York, USA',
  'North Carolina, USA',
  'North Dakota, USA',
  'Ohio, USA',
  'Oklahoma, USA',
  'Oregon, USA',
  'Pennsylvania, USA',
  'Rhode Island, USA',
  'South Carolina, USA',
  'South Dakota, USA',
  'Tennessee, USA',
  'Texas, USA',
  'Utah, USA',
  'Vermont, USA',
  'Virginia, USA',
  'Washington, USA',
  'West Virginia, USA',
  'Wisconsin, USA',
  'Wyoming, USA',

  // Major International Cities
  'Amsterdam, Netherlands',
  'Athens, Greece',
  'Auckland, New Zealand',
  'Bangkok, Thailand',
  'Barcelona, Spain',
  'Beijing, China',
  'Berlin, Germany',
  'Bogotá, Colombia',
  'Brussels, Belgium',
  'Buenos Aires, Argentina',
  'Cairo, Egypt',
  'Cape Town, South Africa',
  'Casablanca, Morocco',
  'Copenhagen, Denmark',
  'Delhi, India',
  'Dubai, UAE',
  'Dublin, Ireland',
  'Edinburgh, UK',
  'Frankfurt, Germany',
  'Geneva, Switzerland',
  'Guangzhou, China',
  'Helsinki, Finland',
  'Ho Chi Minh City, Vietnam',
  'Hong Kong',
  'Istanbul, Turkey',
  'Jakarta, Indonesia',
  'Johannesburg, South Africa',
  'Karachi, Pakistan',
  'Kuala Lumpur, Malaysia',
  'Lagos, Nigeria',
  'Lima, Peru',
  'Lisbon, Portugal',
  'London, UK',
  'Madrid, Spain',
  'Manchester, UK',
  'Manila, Philippines',
  'Melbourne, Australia',
  'Mexico City, Mexico',
  'Milan, Italy',
  'Montreal, Canada',
  'Moscow, Russia',
  'Mumbai, India',
  'Munich, Germany',
  'Nairobi, Kenya',
  'Oslo, Norway',
  'Paris, France',
  'Prague, Czech Republic',
  'Rome, Italy',
  'Santiago, Chile',
  'São Paulo, Brazil',
  'Seoul, South Korea',
  'Shanghai, China',
  'Singapore',
  'Stockholm, Sweden',
  'Sydney, Australia',
  'Taipei, Taiwan',
  'Tel Aviv, Israel',
  'Tokyo, Japan',
  'Toronto, Canada',
  'Vancouver, Canada',
  'Vienna, Austria',
  'Warsaw, Poland',
  'Zurich, Switzerland',
  'Abu Dhabi, UAE',
  'Accra, Ghana',
  'Addis Ababa, Ethiopia',
  'Amman, Jordan',
  'Bangalore, India',
  'Beirut, Lebanon',
  'Brisbane, Australia',
  'Calgary, Canada',
  'Chennai, India',
  'Colombo, Sri Lanka',
  'Dhaka, Bangladesh',
  'Doha, Qatar',
  'Hanoi, Vietnam',
  'Hyderabad, India',
  'Kathmandu, Nepal',
  'Kiev, Ukraine',
  'Kolkata, India',
  'Lahore, Pakistan',
  'Muscat, Oman',
  'Ottawa, Canada',
  'Perth, Australia',
  'Riyadh, Saudi Arabia',
  'Tunis, Tunisia',

  // Countries (for broad location)
  'Argentina',
  'Australia',
  'Austria',
  'Bangladesh',
  'Belgium',
  'Brazil',
  'Canada',
  'Chile',
  'China',
  'Colombia',
  'Czech Republic',
  'Denmark',
  'Egypt',
  'Ethiopia',
  'Finland',
  'France',
  'Germany',
  'Ghana',
  'Greece',
  'Hungary',
  'India',
  'Indonesia',
  'Ireland',
  'Israel',
  'Italy',
  'Japan',
  'Jordan',
  'Kenya',
  'Malaysia',
  'Mexico',
  'Morocco',
  'Netherlands',
  'New Zealand',
  'Nigeria',
  'Norway',
  'Pakistan',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Romania',
  'Russia',
  'Saudi Arabia',
  'South Africa',
  'South Korea',
  'Spain',
  'Sri Lanka',
  'Sweden',
  'Switzerland',
  'Taiwan',
  'Thailand',
  'Turkey',
  'UAE',
  'Uganda',
  'UK',
  'Ukraine',
  'United States',
  'Vietnam',
];

export function searchLocations(query: string): string[] {
  if (!query.trim()) return [...LOCATIONS].sort();
  const q = query.toLowerCase();
  const startsWith = LOCATIONS.filter(loc => loc.toLowerCase().startsWith(q)).sort();
  const contains = LOCATIONS.filter(loc => !loc.toLowerCase().startsWith(q) && loc.toLowerCase().includes(q)).sort();
  return [...startsWith, ...contains];
}
